using System;
using System.Collections.Generic;


namespace Youtube_Music_Downloader {
	internal class SongInfo {
		public string Title { get; private set; } = "";
		public string Album { get; private set; } = "";
		public List<string> Performers { get; private set; } = new List<string>();
		public List<string> Composers { get; private set; } = new List<string>();
		public uint ReleaseYear { get; private set; } = 0;


		public SongInfo(string fileName, Download download) {
			var filenameData = fileName.Split('-');
			Performers.Add(filenameData[0].Trim());
			Title = filenameData[1].Trim();

			var lines = download.Video.Description.Split(new string[] { "\n\n", "\n" }, StringSplitOptions.None);
			if(lines[lines.Length - 1].Equals("Auto-generated by YouTube.")) {
				Album = lines[2];

				foreach(string line in lines) {
					if(line.Contains("Released on")) {
						var indexStartDate = line.IndexOf(":") + 2;
						var date = (line.Substring(indexStartDate, (line.Length - indexStartDate)));
						var dateInfos = date.Split('-');

						ReleaseYear = Convert.ToUInt32(dateInfos[0]);
					}
					else if(line.Contains("Composer")) {
						var indexStart = line.IndexOf(":") + 2;
						var composer = (line.Substring(indexStart, (line.Length - indexStart)));

						Composers.Add(composer);
					}
				}
			}

			if(ReleaseYear == 0)
				ReleaseYear = (uint) download.Video.UploadDate.Year;
		}
	}
}
